language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install python-lxml
install:
  - pip install git+https://github.com/tryton/trytond.git@3.0
  - python setup.py install
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
